/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import java.sql.ResultSet;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.view.JasperViewer;


public class issuereturn extends javax.swing.JFrame {

   
    public issuereturn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        issue = new javax.swing.JButton();
        returnbook2 = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        book = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtissuememberid = new javax.swing.JTextField();
        txtissuemembername = new javax.swing.JTextField();
        txtissuememberbookisbn = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        txtissuereturndate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtissuememberbookname = new javax.swing.JTextField();
        AddIssuebtn = new javax.swing.JButton();
        issueupdatebtn = new javax.swing.JButton();
        issuedeletebtn = new javax.swing.JButton();
        issueviewbtn = new javax.swing.JButton();
        txtissuedeleteid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtissueid = new javax.swing.JTextField();
        viewbookbtn2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable15 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtissueid2 = new javax.swing.JTextField();
        addreturnbtn = new javax.swing.JButton();
        viewreturnbtn = new javax.swing.JButton();
        deletereturnbtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtdayselap = new javax.swing.JTextField();
        txtfine = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtreturndeleteid2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtreturnid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txttodaydate = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        returndetailsbtn = new javax.swing.JButton();
        txtstatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));

        issue.setBackground(new java.awt.Color(102, 0, 0));
        issue.setText("Issue book");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });

        returnbook2.setBackground(new java.awt.Color(102, 0, 0));
        returnbook2.setText("Return book");
        returnbook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbook2ActionPerformed(evt);
            }
        });

        dashboard.setBackground(new java.awt.Color(102, 0, 0));
        dashboard.setText("Dashboard");
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });

        reportbtn.setBackground(new java.awt.Color(102, 0, 0));
        reportbtn.setText("Report");
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnbook2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dashboard, issue, reportbtn, returnbook2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(returnbook2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(reportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dashboard, issue, reportbtn, returnbook2});

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 51, 0));
        jPanel3.setLayout(null);

        jLabel1.setText("Member Id");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 46, 58, 30);

        jLabel2.setText("Member Name");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 80, 80, 20);

        jLabel3.setText("Book ISBN");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 110, 55, 16);

        jLabel4.setText("Issue Date");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 170, 53, 16);

        jLabel5.setText("Return Date");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 200, 62, 20);

        txtissuememberid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtissuememberidKeyTyped(evt);
            }
        });
        jPanel3.add(txtissuememberid);
        txtissuememberid.setBounds(108, 50, 150, 26);

        txtissuemembername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtissuemembernameActionPerformed(evt);
            }
        });
        jPanel3.add(txtissuemembername);
        txtissuemembername.setBounds(108, 80, 150, 26);
        jPanel3.add(txtissuememberbookisbn);
        txtissuememberbookisbn.setBounds(108, 110, 150, 26);

        txtissuedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtissuedateActionPerformed(evt);
            }
        });
        jPanel3.add(txtissuedate);
        txtissuedate.setBounds(108, 170, 150, 26);
        jPanel3.add(txtissuereturndate);
        txtissuereturndate.setBounds(108, 200, 150, 26);

        jLabel6.setText("Book Name");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 140, 70, 16);

        txtissuememberbookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtissuememberbooknameActionPerformed(evt);
            }
        });
        jPanel3.add(txtissuememberbookname);
        txtissuememberbookname.setBounds(108, 140, 150, 26);

        AddIssuebtn.setText("Add");
        AddIssuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIssuebtnActionPerformed(evt);
            }
        });
        jPanel3.add(AddIssuebtn);
        AddIssuebtn.setBounds(10, 270, 110, 40);

        issueupdatebtn.setText("Update");
        issueupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueupdatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(issueupdatebtn);
        issueupdatebtn.setBounds(10, 320, 110, 40);

        issuedeletebtn.setText("Delete");
        issuedeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedeletebtnActionPerformed(evt);
            }
        });
        jPanel3.add(issuedeletebtn);
        issuedeletebtn.setBounds(10, 370, 100, 40);

        issueviewbtn.setText("View Issue Details");
        issueviewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueviewbtnActionPerformed(evt);
            }
        });
        jPanel3.add(issueviewbtn);
        issueviewbtn.setBounds(130, 320, 140, 40);
        jPanel3.add(txtissuedeleteid);
        txtissuedeleteid.setBounds(120, 380, 130, 26);

        jTable7.setBackground(new java.awt.Color(255, 255, 255));
        jTable7.setForeground(new java.awt.Color(0, 0, 0));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue Id", "Member Id", "Member Name", "Book ISBN", "Book Name", "Issue date", "Return date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable7.setGridColor(new java.awt.Color(0, 0, 204));
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable7MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable7);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(300, 330, 800, 250);

        jLabel7.setText("Issue Id");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 26, 50, 20);
        jPanel3.add(txtissueid);
        txtissueid.setBounds(108, 20, 150, 26);

        viewbookbtn2.setText("View Book Details");
        viewbookbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbookbtn2ActionPerformed(evt);
            }
        });
        jPanel3.add(viewbookbtn2);
        viewbookbtn2.setBounds(130, 270, 140, 40);

        jTable15.setBackground(new java.awt.Color(255, 255, 255));
        jTable15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ISBN", "Category", "Book Name", "Author", "Publisher", "Book Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable15MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable15);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(300, 30, 790, 260);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Book Details");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(590, 0, 110, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Issue Details");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(620, 290, 100, 30);

        book.addTab("tab1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 51, 0));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Issue Id");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 70, 70, 21);

        txtissueid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtissueid2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtissueid2);
        txtissueid2.setBounds(110, 70, 90, 26);

        addreturnbtn.setText("Add");
        addreturnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addreturnbtnActionPerformed(evt);
            }
        });
        jPanel4.add(addreturnbtn);
        addreturnbtn.setBounds(0, 280, 100, 50);

        viewreturnbtn.setText("Issue Details");
        viewreturnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreturnbtnActionPerformed(evt);
            }
        });
        jPanel4.add(viewreturnbtn);
        viewreturnbtn.setBounds(110, 280, 98, 50);

        deletereturnbtn.setText("Delete");
        deletereturnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletereturnbtnActionPerformed(evt);
            }
        });
        jPanel4.add(deletereturnbtn);
        deletereturnbtn.setBounds(6, 487, 80, 50);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("Days Elap");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 150, 90, 21);

        txtdayselap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdayselapActionPerformed(evt);
            }
        });
        jPanel4.add(txtdayselap);
        txtdayselap.setBounds(110, 150, 90, 26);
        jPanel4.add(txtfine);
        txtfine.setBounds(110, 190, 90, 26);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("Fine");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 190, 60, 21);

        jTable9.setBackground(new java.awt.Color(255, 255, 255));
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue Id", "Member Id", "Member Name", "Book ISBN", "Book Name", "Issue date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable9MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable9);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(210, 40, 670, 300);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("Status");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(10, 230, 70, 30);
        jPanel4.add(txtreturndeleteid2);
        txtreturndeleteid2.setBounds(100, 500, 100, 26);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("Return Id");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 30, 70, 20);
        jPanel4.add(txtreturnid);
        txtreturnid.setBounds(110, 30, 90, 26);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Today Date");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 110, 90, 21);
        jPanel4.add(txttodaydate);
        txttodaydate.setBounds(110, 110, 90, 26);

        jTable10.setBackground(new java.awt.Color(255, 255, 255));
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue Id", "Return Id", "Today Date", "Days Elap", "Fine", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable10MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable10);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(210, 390, 670, 230);

        returndetailsbtn.setText("Return Details");
        returndetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returndetailsbtnActionPerformed(evt);
            }
        });
        jPanel4.add(returndetailsbtn);
        returndetailsbtn.setBounds(40, 417, 120, 50);
        jPanel4.add(txtstatus);
        txtstatus.setBounds(110, 230, 90, 26);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Issue Details");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(500, 0, 100, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Return Details");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(500, 350, 120, 40);

        book.addTab("tab2", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(book, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(book))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        book.setSelectedIndex(0);
    }//GEN-LAST:event_issueActionPerformed

    private void returnbook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbook2ActionPerformed
        book.setSelectedIndex(1);
    }//GEN-LAST:event_returnbook2ActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
       Home db = new Home();
       this.hide();
       db.setVisible(true);
       
    }//GEN-LAST:event_dashboardActionPerformed

    private void txtissuedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtissuedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtissuedateActionPerformed

    private void txtissuemembernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtissuemembernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtissuemembernameActionPerformed

    private void txtissuememberidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtissuememberidKeyTyped
       
    }//GEN-LAST:event_txtissuememberidKeyTyped

    private void txtissuememberbooknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtissuememberbooknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtissuememberbooknameActionPerformed

    private void AddIssuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIssuebtnActionPerformed
         try{
        int issueid=Integer.parseInt(txtissueid.getText());
        String issuememberid=txtissuememberid.getText();
        String issuemembername=txtissuemembername.getText();
        String issuememberbookisbn=txtissuememberbookisbn.getText();
        String issuememberbookname=txtissuememberbookname.getText();
        String issuedate=txtissuedate.getText();
        String issuereturndate=txtissuereturndate.getText();
      
        CissueANDreturn Ciar=new CissueANDreturn();
        Ciar.addIssuedetails(issueid,issuememberid,issuemembername,issuememberbookisbn,issuememberbookname,issuedate,issuereturndate);
       
       
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs4 = Crb.IssueViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable7.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs4.next())
            {
               model.addRow(new String[]{rs4.getString(1),rs4.getString(2),rs4.getString(3),rs4.getString(4),rs4.getString(5),rs4.getString(6),rs4.getString(7)});
         
            }
        
        }
          
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null," Invalid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }//GEN-LAST:event_AddIssuebtnActionPerformed

    private void jTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseClicked
        DefaultTableModel md4 = (DefaultTableModel)jTable7.getModel();
        int selectIndex = jTable7.getSelectedRow();
        
         txtissueid.setText(md4.getValueAt(selectIndex, 0).toString());
         txtissuememberid.setText(md4.getValueAt(selectIndex,1).toString());
         txtissuemembername.setText(md4.getValueAt(selectIndex,2).toString());
         txtissuememberbookisbn.setText(md4.getValueAt(selectIndex,3).toString());
         txtissuememberbookname.setText(md4.getValueAt(selectIndex,4).toString());
         txtissuedate.setText(md4.getValueAt(selectIndex,5).toString());
         txtissuereturndate.setText(md4.getValueAt(selectIndex,6).toString());
        
         //delete karana id eka ganna wa table eken 
         txtissuedeleteid.setText(md4.getValueAt(selectIndex, 0).toString());
    }//GEN-LAST:event_jTable7MouseClicked

    private void issueviewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueviewbtnActionPerformed
        try{ 
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs4 = Crb.IssueViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable7.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs4.next())
            {
               model.addRow(new String[]{rs4.getString(1),rs4.getString(2),rs4.getString(3),rs4.getString(4),rs4.getString(5),rs4.getString(6),rs4.getString(7)});
         
            }
        
        }
          
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null," Invalid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
       
    }//GEN-LAST:event_issueviewbtnActionPerformed

    private void issueupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueupdatebtnActionPerformed
        try{
        int issueid=Integer.parseInt(txtissueid.getText());
        String issuememberid=txtissuememberid.getText();
        String issuemembername=txtissuemembername.getText();
        String issuememberbookisbn=txtissuememberbookisbn.getText();
        String issuememberbookname=txtissuememberbookname.getText();
        String issuedate=txtissuedate.getText();
        String issuereturndate=txtissuereturndate.getText();
      
        CissueANDreturn Ciar=new CissueANDreturn();
        Ciar.updateIssuedetails(issueid,issuememberid,issuemembername,issuememberbookisbn,issuememberbookname,issuedate,issuereturndate);
       
       
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs4 = Crb.IssueViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable7.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs4.next())
            {
               model.addRow(new String[]{rs4.getString(1),rs4.getString(2),rs4.getString(3),rs4.getString(4),rs4.getString(5),rs4.getString(6),rs4.getString(7)});
         
            }
        
        }
          
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null," Invalid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }//GEN-LAST:event_issueupdatebtnActionPerformed

    private void issuedeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedeletebtnActionPerformed
        try{
       
        int deleteissueid=Integer.parseInt(txtissuedeleteid.getText());
        
       CissueANDreturn Ciar=new CissueANDreturn();
       Ciar.deleteIssuedetails(deleteissueid);
       
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs4 = Crb.IssueViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable7.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs4.next())
            {
               model.addRow(new String[]{rs4.getString(1),rs4.getString(2),rs4.getString(3),rs4.getString(4),rs4.getString(5),rs4.getString(6),rs4.getString(7)});
         
            }
        
        }
          
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null," Invalid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }//GEN-LAST:event_issuedeletebtnActionPerformed

    private void txtissueid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtissueid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtissueid2ActionPerformed

    private void txtdayselapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdayselapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdayselapActionPerformed

    private void jTable9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable9MouseClicked
         DefaultTableModel md4 = (DefaultTableModel)jTable9.getModel();
         int selectIndex = jTable9.getSelectedRow();
        
         txtissueid2.setText(md4.getValueAt(selectIndex, 0).toString());
        
        
         //delete karana id eka ganna wa table eken 
         
    }//GEN-LAST:event_jTable9MouseClicked

    private void viewreturnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreturnbtnActionPerformed
       try{ 
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs4 = Crb.IssueViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable9.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs4.next())
            {
               model.addRow(new String[]{rs4.getString(1),rs4.getString(2),rs4.getString(3),rs4.getString(4),rs4.getString(5),rs4.getString(6),rs4.getString(7)});
         
            }
        
        }
          
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null," Invalid Data Type","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }//GEN-LAST:event_viewreturnbtnActionPerformed

    private void addreturnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addreturnbtnActionPerformed
        try{
        int returnid=Integer.parseInt(txtreturnid.getText());
        int issueid2=Integer.parseInt(txtissueid2.getText());
        String todaydate=txttodaydate.getText();
        int dayselap=Integer.parseInt(txtdayselap.getText());
        String fine=txtfine.getText();
        String status=txtstatus.getText();
       
      
        CissueANDreturn Ciar=new CissueANDreturn();
        Ciar.addreturndetails(returnid,issueid2,todaydate,dayselap,fine,status);
       
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs5 = Crb.returnViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable10.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs5.next())
            {
               model.addRow(new String[]{rs5.getString(1),rs5.getString(2),rs5.getString(3),rs5.getString(4),rs5.getString(5),rs5.getString(6)});
         
            }
        
        }
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null,"Enter Invalid Data","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }//GEN-LAST:event_addreturnbtnActionPerformed

    private void deletereturnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletereturnbtnActionPerformed
        try{
       
        int returndeleteid=Integer.parseInt(txtreturndeleteid2.getText());
        
       CissueANDreturn Ciar=new CissueANDreturn();
       Ciar.deletereturndetails(returndeleteid);
       
       
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs5 = Crb.returnViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable10.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs5.next())
            {
               model.addRow(new String[]{rs5.getString(1),rs5.getString(2),rs5.getString(3),rs5.getString(4),rs5.getString(5),rs5.getString(6)});
         
            }
        
        }
          
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null,"Enter Invalid Data","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }//GEN-LAST:event_deletereturnbtnActionPerformed

    private void returndetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returndetailsbtnActionPerformed
       try{ 
        CissueANDreturn Crb=new CissueANDreturn();
        ResultSet rs5 = Crb.returnViewDetails();
        DefaultTableModel model = (DefaultTableModel)jTable10.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs5.next())
            {
               model.addRow(new String[]{rs5.getString(1),rs5.getString(2),rs5.getString(3),rs5.getString(4),rs5.getString(5),rs5.getString(6)});
         
            }
        
        }
          
        
        catch(NumberFormatException ex2)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid Data","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(InputMismatchException ex3)
        {
            JOptionPane.showMessageDialog(null,"Enter Invalid Data","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        catch(NullPointerException ex4)
        {
            JOptionPane.showMessageDialog(null, "Do not view null Data ","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
    }//GEN-LAST:event_returndetailsbtnActionPerformed

    private void jTable10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable10MouseClicked
         DefaultTableModel md4 = (DefaultTableModel)jTable10.getModel();
         int selectIndex = jTable10.getSelectedRow();
   
        
         //delete karana id eka ganna wa table eken 
         txtreturndeleteid2.setText(md4.getValueAt(selectIndex, 1).toString());
    }//GEN-LAST:event_jTable10MouseClicked

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        try{
    String dbpath = "jdbc:mysql://localhost/library";
    Connection con =DriverManager.getConnection(dbpath,"root","");
    JasperDesign jdesign=JRXmlLoader.load("E:\\software engineer\\4th term\\3enterprise application development\\exercise\\coursewk\\src\\view\\report1.jrxml");
    JRDesignQuery jquery =new JRDesignQuery();
    
    String sqlquery="select * from issuedetails,returndetails where issuedetails.issueid=returndetails.returnid";
    jquery.setText(sqlquery);
    jdesign.setQuery(jquery);
    JasperReport rpt = JasperCompileManager.compileReport(jdesign);
    JasperPrint print = JasperFillManager.fillReport(rpt,null,con);
    JasperViewer.viewReport(print);
    
    }
    
    catch(Exception e)
    {
         JOptionPane.showMessageDialog(rootPane,e.getMessage());

    }
        
    }//GEN-LAST:event_reportbtnActionPerformed

    private void viewbookbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbookbtn2ActionPerformed
         try{ 
        Creaderbook Crb=new Creaderbook();
        ResultSet rs = Crb.viewBookDetails();
        DefaultTableModel model = (DefaultTableModel)jTable15.getModel();
        //repeat nowiimata
        model.setRowCount(0);
            
            while(rs.next())
            {
               model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
         
            }
        }
        
   
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage()); 
        }
       
    }//GEN-LAST:event_viewbookbtn2ActionPerformed

    private void jTable15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable15MouseClicked
         DefaultTableModel md2 = (DefaultTableModel)jTable15.getModel();
         int selectIndex = jTable15.getSelectedRow();
        
         txtissuememberbookisbn.setText(md2.getValueAt(selectIndex, 0).toString());
         txtissuememberbookname.setText(md2.getValueAt(selectIndex,2).toString());
        

         
    }//GEN-LAST:event_jTable15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuereturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuereturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuereturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuereturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuereturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIssuebtn;
    private javax.swing.JButton addreturnbtn;
    private javax.swing.JTabbedPane book;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton deletereturnbtn;
    private javax.swing.JButton issue;
    private javax.swing.JButton issuedeletebtn;
    private javax.swing.JButton issueupdatebtn;
    private javax.swing.JButton issueviewbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable9;
    private javax.swing.JButton reportbtn;
    private javax.swing.JButton returnbook2;
    private javax.swing.JButton returndetailsbtn;
    private javax.swing.JTextField txtdayselap;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtissuedeleteid;
    private javax.swing.JTextField txtissueid;
    private javax.swing.JTextField txtissueid2;
    private javax.swing.JTextField txtissuememberbookisbn;
    private javax.swing.JTextField txtissuememberbookname;
    private javax.swing.JTextField txtissuememberid;
    private javax.swing.JTextField txtissuemembername;
    private javax.swing.JTextField txtissuereturndate;
    private javax.swing.JTextField txtreturndeleteid2;
    private javax.swing.JTextField txtreturnid;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JTextField txttodaydate;
    private javax.swing.JButton viewbookbtn2;
    private javax.swing.JButton viewreturnbtn;
    // End of variables declaration//GEN-END:variables
}
